# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_remove_item_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pub_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='pub_date_resolution',
            field=models.CharField(choices=[(b'm', b'Month'), (b'w', b'Week'), (b'd', b'Day'), (b't', b'Time')], default=b'd', editable=False, max_length=1, null=True),
        ),
    ]
