# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0039_contentplacement_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='computed_contributor_names',
            field=models.TextField(blank=True, help_text=b'An auto-generated list of all editors and authors for this item. Re-generated every time the item is saved.', null=True),
        ),
    ]
