# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 23:27
from __future__ import unicode_literals

from django.db import migrations


def generate_item_contributor_names(apps, schema_editor):
    Item = apps.get_model('budget', 'Item')

    for item in Item.objects.all():
        author_names = []
        editor_names = []

        if item.authors is not None:
            author_names = [_['full_name'] for _ in item.authors]

        if item.editors is not None:
            editor_names = [_['full_name'] for _ in item.editors]

        item.computed_contributor_names = ' '.join(author_names + editor_names)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0040_item_computed_contributor_names'),
    ]

    operations = [
        migrations.RunPython(generate_item_contributor_names),
    ]
