# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-14 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
